Use more idiomatic `deno_assets` attribute names
denoland/terraform-provider-deno pull request #9
Opened 2023-10-08 21:42 UTC by piscisaureus

2023-10-09 12:09 UTC, magurotuna commented on examples/provider-install-verification/main.tf
> -resource "deno_certificate_provisioning" "example_certificate_provisioning" {
I see no change in the resource name in the resource definition. Is this change intended to be included in this PR?

2023-10-10 02:00 UTC, magurotuna requested changes

2023-10-10 02:00 UTC, magurotuna commented on examples/resources/deno_certificate_provisioning/resource.tf
Ditto (directory name needs to match the resource name so doc generator can use it)

2023-10-10 02:29 UTC, piscisaureus commented on internal/provider/certificate_provisioning_resource.go
good catch!

2023-10-10 02:29 UTC, piscisaureus commented on examples/resources/deno_certificate_provisioning/resource.tf
ditto!

2023-10-10 03:33 UTC, magurotuna approved these changes
LGTM

2023-10-10 03:50 UTC, merged